import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(root, '.env');
const outputPath = resolve(root, 'src/environments/environment.generated.ts');

const defaults = {
  NG_APP_API_URL: 'http://localhost:3000',
};

function parseEnvFile(content) {
  const vars = { ...defaults };

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const separator = trimmed.indexOf('=');
    if (separator === -1) continue;

    const key = trimmed.slice(0, separator).trim();
    let value = trimmed.slice(separator + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    vars[key] = value;
  }

  return vars;
}

function loadEnv() {
  const vars = { ...defaults };

  if (existsSync(envPath)) {
    Object.assign(vars, parseEnvFile(readFileSync(envPath, 'utf8')));
  }

  for (const key of Object.keys(defaults)) {
    if (process.env[key]) {
      vars[key] = process.env[key];
    }
  }

  return vars;
}

const { NG_APP_API_URL } = loadEnv();

const content = `// Auto-generated by scripts/generate-env.mjs — do not edit.
export const generatedEnvironment = {
  apiUrl: ${JSON.stringify(NG_APP_API_URL)},
};
`;

writeFileSync(outputPath, content, 'utf8');
console.log(`Generated ${outputPath} (apiUrl=${NG_APP_API_URL})`);
